# Generated by Django 5.1.1 on 2024-10-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
