# Generated by Django 5.1.1 on 2024-10-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_myuser_store_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='store_name',
        ),
    ]
