# Generated by Django 5.1.1 on 2024-11-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_shoppinglist_shoppinglistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/%y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
