# Generated by Django 5.1.1 on 2024-11-07 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_store_alter_shoppinglist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_owner',
            field=models.ManyToManyField(blank=True, related_name='managed_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
