# Generated by Django 5.1.1 on 2024-11-07 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_store_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='store_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='myapp.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='store_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.store'),
            preserve_default=False,
        ),
    ]
