# Generated by Django 5.1.1 on 2024-11-16 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_size', models.PositiveIntegerField(default=50)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layout', to='myapp.store')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.BigIntegerField(unique=True)),
                ('type', models.CharField(max_length=50)),
                ('position_x', models.PositiveIntegerField()),
                ('position_y', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('categories', models.JSONField(default=list)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='myapp.storelayout')),
            ],
        ),
    ]
