# Generated by Django 5.1.1 on 2024-11-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_storelayout_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_id',
            field=models.BigIntegerField(),
        ),
    ]
