# Generated by Django 5.1.1 on 2024-11-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_component_component_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='rotation',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=18),
            preserve_default=False,
        ),
    ]
